# Generated by Django 6.0.1 on 2026-02-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
