# Generated by Django 6.0.1 on 2026-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeingredientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientimage',
            name='extracted',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
